### ISSUE TITLE
Technic general TODO list

### ISSUE THREAD

**Issue by SmallJoker** [minetest-mods/technic#601]
Help us to make Technic a better mod! But what to do?

- [ ] Incrementally switch to `.tr` client-side translations. Deprecate intllib.
    * Hints: `minetest.get_translator`, https://github.com/minetest-tools/update_translations
- [ ] Replace `itemstack:get_metadata()` with `itemstack:get_meta()`
    * Needs a compatibility function to migrate existing items, for example `technic.get_stack_meta_compat(itemstack)`
- [ ] General code maintenance.
    * De-duplicate code
    * Move repeated operations into variables or functions
    * Check for unused functions and purge them
- [ ] Textures: The furnace front texture does not match the sides. Needs color adjustment and/or new textures.

Each point will need a separate Pull Request (and commit). This is my personal list, but the tasks will not be done anytime soon, hence contributions are much appreciated!

**Comment by OgelGames** [comment]
The first task already has a PR: https://github.com/minetest-mods/technic/pull/529

**Comment by MidnightPhantom** [comment]
Hey Please add the recycler, that would turn your trash into basic materials
